const express = require("express");
const router = express.Router();
const Synonym = require("../Models/synonymModel");
const SynonymSuggestion = require("../Models/synonymSuggestionModel");
const SUGGESTION_THRESHOLD = 10;

// ADD SYNONYM
router.post("/add", async (req, res) => {

  const {
    query,
    synonym,
    store
  } = req.body;

  const normalizedStore =
    store?.trim()?.toLowerCase();

  const normalizedQuery =
    query?.trim()?.toLowerCase();

  const normalizedSynonym =
    synonym?.trim()?.toLowerCase();

  if (
    !query ||
    !synonym ||
    !store
  ) {

    return res.status(400).json({
      error:
        "Query, synonym and store are required"
    });

  }

  try {

    const existing =
      await Synonym.findOne({

        query:
          normalizedQuery,

        store:
          normalizedStore

      });

    if (existing) {

      if (

        !existing.synonyms.some(

          s =>
            s.word ===
            normalizedSynonym

        )

      ) {

        existing.synonyms.push({

          word:
            normalizedSynonym,

          usageCount: 1,

          autoGenerated: false,

          confidence: 1

        });

      }

      await existing.save();

      return res.json(existing);

    }

    const newSynonym =
      await Synonym.create({

        query:
          normalizedQuery,

        synonyms: [

          {

            word:
              normalizedSynonym,

            usageCount: 1,

            autoGenerated: false,

            confidence: 1

          }

        ],

        store:
          normalizedStore

      });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});


// =========================
// 📋 LIST SYNONYMS
// =========================
router.get("/list", async (req, res) => {

  try {

    const { store } = req.query;

    const normalizedStore =
      store?.trim()?.toLowerCase();

    if (!store) {

      return res.status(400).json({
        error: "Store is required"
      });

    }

    const synonyms =
      await Synonym
        .find({
          store:
            normalizedStore
        })
        .sort({
          createdAt: -1
        })
        .lean();

    res.json({
      synonyms
    });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});

// =========================
// 🗑 DELETE SYNONYM
// =========================
router.delete("/delete/:id", async (req, res) => {

  try {

    const { store } = req.body;

    const normalizedStore =
      store?.trim()?.toLowerCase();

    if (!store) {

      return res.status(400).json({
        error: "Store is required"
      });

    }

    await Synonym.findOneAndDelete({

      _id: req.params.id,

      store:
        normalizedStore

    });

    res.json({
      success: true
    });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});

// =========================
// 📋 LIST PENDING SYNONYM SUGGESTIONS
// GET /api/synonyms/suggestions?shop=xxx&status=pending
// Returns popular queries (count >= threshold) that need admin review
// =========================
router.get("/suggestions", async (req, res) => {
  try {
    const { store, shop, status = "pending" } = req.query;
    const normalizedStore = (store || shop)?.trim()?.toLowerCase();
    if (!normalizedStore) return res.status(400).json({ error: "Store required" });

    const suggestions = await SynonymSuggestion.find({
      store: normalizedStore,
      status,
      count: { $gte: SUGGESTION_THRESHOLD }
    })
      .sort({ count: -1 })
      .limit(100)
      .lean();

    res.json({ suggestions, threshold: SUGGESTION_THRESHOLD });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// =========================
// ✅ APPROVE SUGGESTION
// POST /api/synonyms/suggestions/:id/approve
// body: { shop, synonymFor? }
// synonymFor = existing query this becomes synonym of (optional)
// If omitted → creates a new standalone synonym entry
// =========================
router.post("/suggestions/:id/approve", async (req, res) => {
  try {
    const { store, shop, synonymFor } = req.body;
    const normalizedStore = (store || shop)?.trim()?.toLowerCase();
    if (!normalizedStore) return res.status(400).json({ error: "Store required" });

    const suggestion = await SynonymSuggestion.findOne({ _id: req.params.id, store: normalizedStore });
    if (!suggestion) return res.status(404).json({ error: "Suggestion not found" });

    const queryWord = suggestion.query.trim().toLowerCase();
    const baseQuery = synonymFor?.trim()?.toLowerCase() || queryWord;

    // Add to Synonym collection
    const existing = await Synonym.findOne({ query: baseQuery, store: normalizedStore });
    if (existing) {
      if (!existing.synonyms.some(s => s.word === queryWord)) {
        existing.synonyms.push({ word: queryWord, usageCount: suggestion.count, autoGenerated: true, confidence: 0.9 });
        await existing.save({ validateBeforeSave: false });
      }
    } else {
      await Synonym.create({
        query: baseQuery,
        store: normalizedStore,
        synonyms: [{ word: queryWord, usageCount: suggestion.count, autoGenerated: true, confidence: 0.9 }]
      });
    }

    suggestion.status = "approved";
    suggestion.approvedAs = baseQuery;
    await suggestion.save();

    res.json({ success: true, approvedAs: baseQuery });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// =========================
// ❌ REJECT SUGGESTION
// POST /api/synonyms/suggestions/:id/reject
// body: { shop }
// =========================
router.post("/suggestions/:id/reject", async (req, res) => {
  try {
    const { store, shop } = req.body;
    const normalizedStore = (store || shop)?.trim()?.toLowerCase();
    if (!normalizedStore) return res.status(400).json({ error: "Store required" });

    await SynonymSuggestion.findOneAndUpdate(
      { _id: req.params.id, store: normalizedStore },
      { status: "rejected" }
    );
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;